package events;

import human.Nurse;
import human.Patient;
import others.Database;
import others.IDGeneratorEvent;
import rooms.Room;

public class Installation extends Event{
	
	private Nurse nurse;
	private Patient patient;
	private Room room;
	
	/**
	 * Constructs an installation Event.
	 * <br>The ID is generated by the getNextID Method.
	 * <br>The occurence time is the current time.
	 * @param edName The ED in which the event is created.
	 */
	public Installation(String edName) {
		this.ed = Database.getEDbyName(edName);
		this.id=IDGeneratorEvent.getInstance().getNextID();
		this.name = "Patient Installation" + String.valueOf(this.id);
		this.occurenceTime = Database.getTime();
		this.patient=this.ed.getNextRegisteredPatient();
		this.type= "Installation";
	}
	
	/**
	 * Constructs aan installation Event.
	 * <br>The ID is generated by the getNextID Method.
	 * <br>The occurence time is the current time.
	 * @param edName The ED in which the event is created.
	 * @param patient The patient being installed
	 * @param nurse the nurse installing the patient
	 * @param room the room in which the patient is installed.
	 */
	public Installation(String edName, Patient patient, Nurse nurse, Room room) {
		this.ed = Database.getEDbyName(edName);
		this.id=IDGeneratorEvent.getInstance().getNextID();
		this.name = "Patient Installation" + String.valueOf(this.id);
		this.occurenceTime = Database.getTime();
		this.nurse = nurse;
		this.patient = patient;
		this.room = room;
		this.type= "Installation";
	}
	
	public Nurse getNurse() {
		return nurse;
	}

	public Patient getPatient() {
		return patient;
	}

	public Room getRoom() {
		return room;
	}

	/**
	 * This choose a nurse for the next installation.
	 * if the patient is L1 or L2 and a schock room is available, it is choosen, else, a boxroom is chosen.
	 * The installation and the endOfInstallation is triggered
	 */
	@Override
	public void execute() {
		this.nurse=this.ed.getNextNurse();
		if (this.patient.getLevel()<=2 & this.ed.getNextEmptyShockRoom() != null) {
			this.room=this.ed.getNextEmptyShockRoom();
		} else {
			this.room=this.ed.getNextEmptyBoxRoom();
		}
		nurse.installation (patient,room);
		this.ed.addToEventQueue(new EndOfInstallation(this));
		this.ed.getNewEnabledEvents().remove("Installation");
	}
}
