package events;

import human.Patient;
import others.Database;
import others.IDGeneratorEvent;

public class PatientArrival extends Event {
	
	private Patient patient;
	
	/**
	 * This constructs a PatientArrival Event
	 * <br>The ID is generated by the getNextID Method.
	 * @param edName The ED in which the event is created
	 */
	public PatientArrival(String edName){
		this.ed = Database.getEDbyName(edName);
		this.id=IDGeneratorEvent.getInstance().getNextID();
		this.name = "Patient Arrival " + String.valueOf(id);
		this.occurenceTime = patient.getArrivalTime();
		this.type="PatientArrival";
	}
	
	/**
	 * This constructs a PatientArrival Event
	 * <br>The ID is generated by the getNextID Method.
	 * @param edName The ED in which the event is created
	 * @param patient The patient arriving
	 */
	public PatientArrival(String edName, Patient patient){
		this.ed = Database.getEDbyName(edName);
		this.id=IDGeneratorEvent.getInstance().getNextID();
		this.name = "Patient Arrival " + String.valueOf(id);
		this.patient = patient;
		this.occurenceTime = patient.getArrivalTime();
		this.type="PatientArrival";
	}
	
	@Override
	public void execute() {
		this.patient.setState("arrived");
	}
}
