package events;

import java.util.ArrayList;

import human.Nurse;
import human.Patient;
import others.Database;
import others.IDGeneratorEvent;

public class Registration extends Event {
	private Nurse nurse;
	
	/**
	 * Constructs a registration Event.
	 * <br>The ID is generated by the getNextID Method.
	 * <br>The occurence time is the current time.
	 * @param edName The ED in which the event is created.
	 */
	public Registration(String edName) {
		this.ed=Database.getEDbyName(edName);
		this.id=IDGeneratorEvent.getInstance().getNextID();
		this.name=("Registration" + String.valueOf(id));
		this.occurenceTime=(this.ed.getTime());
		this.type= "Registration";
	}
	
	/**
	 * This chose the first nurse idling to register the patients waiting after their arrival.
	 */
	@Override
	public void execute () {
		this.nurse=ed.getNextNurse();
		for (Patient patient:new ArrayList<Patient>(this.ed.getArrivedPatients())) {
			nurse.registration(patient);
			this.ed.getNewEnabledEvents().remove("Registration");
		}	
	}
}
